import { z } from "zod";

export const SURVEY_QUESTION_TYPE_VALUES = ["radio", "checkbox", "text"] as const;
export type SurveyQuestionType = (typeof SURVEY_QUESTION_TYPE_VALUES)[number];

export const FUNNEL_DEPLOYMENT_STATUS_VALUES = ["draft", "ready", "deployed"] as const;
export type FunnelDeploymentStatus = (typeof FUNNEL_DEPLOYMENT_STATUS_VALUES)[number];

export const surveyQuestionInputSchema = z
  .object({
    id: z.number().int().positive().optional(),
    questionText: z.string().trim().min(2, "Enter the question.").max(500),
    questionType: z.enum(SURVEY_QUESTION_TYPE_VALUES),
    options: z.array(z.string().trim().min(1).max(160)).max(20),
  })
  .superRefine((question, context) => {
    const normalizedOptions = question.options.map(option => option.toLowerCase());
    if (new Set(normalizedOptions).size !== normalizedOptions.length) {
      context.addIssue({ code: "custom", path: ["options"], message: "Answer choices must be unique." });
    }

    if (question.questionType === "text" && question.options.length > 0) {
      context.addIssue({ code: "custom", path: ["options"], message: "Text questions do not use answer choices." });
    }

    if (question.questionType !== "text" && question.options.length < 2) {
      context.addIssue({ code: "custom", path: ["options"], message: "Add at least two answer choices." });
    }
  });

export type SurveyQuestionInput = z.infer<typeof surveyQuestionInputSchema>;

export const funnelEditorInputSchema = z.object({
  name: z.string().trim().min(2, "Enter a funnel name.").max(160),
  slug: z
    .string()
    .trim()
    .min(2, "Enter a funnel path.")
    .max(240)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Use lowercase letters, numbers, and hyphens only."),
  serviceArea: z.string().trim().min(2, "Enter the service area.").max(500),
  offerHeadline: z.string().trim().min(3, "Enter the offer headline.").max(300),
  offerSubheadline: z.string().trim().min(3, "Enter the offer subheadline.").max(2000),
  thankYouMessage: z.string().trim().min(3, "Enter the thank-you message.").max(2000),
  questions: z.array(surveyQuestionInputSchema).max(20, "Use no more than 20 survey questions."),
});

export type FunnelEditorInput = z.infer<typeof funnelEditorInputSchema>;

export type FunnelConfigSource = FunnelEditorInput & {
  businessName: string;
  phone: string;
  metaPixelId: string;
  ghlWebhookUrl: string;
};

export function funnelStepCount(questionCount: number): number {
  return questionCount + 3;
}

export function funnelFormStepCount(questionCount: number): number {
  return questionCount + 2;
}

export function defaultServiceArea(input: {
  city: string;
  state: string;
  postalCode: string;
  country: string;
}): string {
  return [input.city, input.state, input.postalCode, input.country]
    .map(value => value.trim())
    .filter(Boolean)
    .join(", ");
}

export function slugifyFunnelName(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

export function generateFunnelConfig(source: FunnelConfigSource): string {
  const config = {
    business: {
      name: source.businessName,
      phone: source.phone,
      serviceArea: source.serviceArea,
    },
    offer: {
      headline: source.offerHeadline,
      subheadline: source.offerSubheadline,
    },
    tracking: {
      metaPixelId: source.metaPixelId,
    },
    integrations: {
      ghlWebhookUrl: source.ghlWebhookUrl,
    },
    steps: [
      {
        id: "zip",
        type: "zip",
        label: "ZIP Code",
        fields: ["zip"],
      },
      ...source.questions.map((question, index) => ({
        id: `survey-${index + 1}`,
        type: "survey",
        question: question.questionText,
        inputType: question.questionType,
        options: question.options,
      })),
      {
        id: "contact",
        type: "contact",
        label: "Contact Information",
        fields: ["firstName", "lastName", "email", "phone"],
      },
      {
        id: "thank-you",
        type: "thankYou",
        message: source.thankYouMessage,
      },
    ],
  };

  return [
    "// Generated by Site Launchpad. Edit in the dashboard and regenerate instead of changing this file.",
    `export const funnelConfig = ${JSON.stringify(config, null, 2)} as const;`,
    "",
    "export type FunnelConfig = typeof funnelConfig;",
    "",
  ].join("\n");
}

export const DEPLOY_SUCCESS_MESSAGE =
  "Funnel config generated. Run `npx wrangler deploy` in the funnel template folder to go live.";
